### ISSUE TITLE
Allow elasticsearch configuration

### ISSUE THREAD

**Issue by Monish-Parajuli** [manishrjain/gocrud#16]
_Problem:_
There is no way to configure elasticsearch (or memsearch)

_Usecase:_
Index versions are taking too much space and I don't need old versions but I don't know exact versions to delete. I want to specify [TTL](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-ttl-field.html) of indexes so old indexes are removed periodically.

_Possible solution:_
- Allow passing elasticsearch options to the search driver (?)
- Expose function to configure the driver(?)
- Something else (?)

**Comment by manishrjain** [comment]
Hey Monish,

You can manage ES configuration outside of Gocrud. Gocrud only populates the ES with updates, and helps you query some limited functionality easily. It doesn't know about internal ES configuration, that's beyond it's scope.

Something to note, Gocrud replaces the previous versions, it doesn't maintain versions of the same entity. So, I guess if the index is getting filled, it's probably due to stale entities. It might also be time to shard ES over to multiple machines, which is relatively easy.

You can follow the TTL config as described by ES, and set it up the same way you set up the `not_analyzed` index.
